# Generated by Django 4.1 on 2014-04-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=35)),
                ('c_founded', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('ind_id', models.AutoField(primary_key=True, serialize=False)),
                ('ind_name', models.CharField(max_length=20)),
            ],
        ),
    ]
