# Generated by Django 4.1 on 2014-04-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='c_industry',
            field=models.ManyToManyField(related_name='companies', to='Api.industry'),
        ),
    ]
