# Generated by Django 4.1 on 2023-05-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0002_movie_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='M_name',
            new_name='g_name',
        ),
    ]
