# Generated by Django 4.1 on 2023-05-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=25)),
                ('u_city', models.CharField(max_length=30)),
                ('u_gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'others')], max_length=1)),
            ],
        ),
    ]
