# Generated by Django 4.1 on 2014-04-21 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('vid_id', models.AutoField(primary_key=True, serialize=False)),
                ('vid_title', models.CharField(max_length=50)),
                ('vid_publish_date', models.DateField()),
                ('vid_views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VTubeUser',
            fields=[
                ('usr_id', models.AutoField(primary_key=True, serialize=False)),
                ('usr_username', models.CharField(max_length=25)),
                ('usr_password', models.CharField(max_length=32)),
                ('usr_email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cmt_id', models.AutoField(primary_key=True, serialize=False)),
                ('cmt_text', models.TextField()),
                ('cmt_usr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='Api.vtubeuser')),
                ('cmt_vid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='Api.video')),
            ],
        ),
    ]
