# Generated by Django 4.1 on 2014-04-22 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('capital', models.CharField(max_length=20)),
                ('population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChfMinister',
            fields=[
                ('cmid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('dob', models.DateField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm', to='Api.state')),
            ],
        ),
    ]
