# Generated by Django 4.1 on 2014-04-22 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chfminister',
            name='state_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cm', to='Api.state'),
        ),
    ]
