# Generated by Django 4.1 on 2014-04-21 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dprt_id', models.AutoField(primary_key=True, serialize=False)),
                ('dprt_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Enployee',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_name', models.CharField(max_length=30)),
                ('e_gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=1)),
                ('e_dob', models.DateField()),
                ('e_salary', models.IntegerField()),
                ('e_email', models.EmailField(max_length=254)),
                ('e_dprt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.department')),
            ],
        ),
    ]
