# Generated by Django 4.1 on 2014-04-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enployee',
            new_name='Employee',
        ),
    ]
