# Generated by Django 4.1 on 2014-04-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='b_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
