# Generated by Django 4.2.18 on 2014-04-21 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=25)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=50)),
                ('author', models.TextField(max_length=25)),
                ('isbn', models.IntegerField()),
                ('is_borrowed', models.BooleanField(default=False)),
                ('borrowed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='Api.member')),
            ],
        ),
    ]
