# Generated by Django 4.2.18 on 2014-04-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_book_borrowed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
