# Generated by Django 4.2.4 on 2014-04-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('pages', models.IntegerField()),
                ('author', models.CharField(max_length=25)),
            ],
        ),
    ]
