# Generated by Django 4.2.4 on 2014-04-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.FileField(default=0, upload_to='covers/'),
            preserve_default=False,
        ),
    ]
